FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/reef /usr/local/bin/reef
COPY $TARGETPLATFORM/reef-launcher /usr/local/bin/reef-launcher
COPY $TARGETPLATFORM/reef-launcher-tui /usr/local/bin/reef-launcher-tui

ENTRYPOINT ["reef-launcher"]
CMD ["-console", "-public", "-no-browser"]
