package evolution

import (
	"fmt"
	"time"
)

// SkillDraftStatus defines the lifecycle states of a SkillDraft.
type SkillDraftStatus string

const (
	SkillDraftPendingReview SkillDraftStatus = "pending_review"
	SkillDraftApproved      SkillDraftStatus = "approved"
	SkillDraftRejected      SkillDraftStatus = "rejected"
	SkillDraftPublished     SkillDraftStatus = "published"
)

// SkillDraft represents a proposed skill generated by the SkillMerger
// from one or more accumulated Genes. It follows a review-then-publish workflow.
type SkillDraft struct {
	ID            string           `json:"id"`
	Role          string           `json:"role"`
	SkillName     string           `json:"skill_name"`
	Content       string           `json:"content"`                 // Raw markdown SKILL.md content
	SourceGeneIDs []string         `json:"source_gene_ids"`         // Gene IDs that contributed
	Status        SkillDraftStatus `json:"status"`
	ReviewComment string           `json:"review_comment,omitempty"` // Filled on reject
	CreatedAt     time.Time        `json:"created_at"`
	ReviewedAt    *time.Time       `json:"reviewed_at,omitempty"`
	PublishedAt   *time.Time       `json:"published_at,omitempty"`
}

// Validate performs local legality checks on the skill draft.
// Returns nil when all checks pass.
func (d *SkillDraft) Validate() []error {
	var errs []error

	if d.ID == "" {
		errs = append(errs, fmt.Errorf("id required"))
	}
	if d.Role == "" {
		errs = append(errs, fmt.Errorf("role required"))
	}
	if d.SkillName == "" {
		errs = append(errs, fmt.Errorf("skill_name required"))
	}
	if d.Content == "" {
		errs = append(errs, fmt.Errorf("content required"))
	}
	if len(d.SourceGeneIDs) == 0 {
		errs = append(errs, fmt.Errorf("at least one source_gene_id required"))
	}

	if len(errs) == 0 {
		return nil
	}
	return errs
}

// CanTransitionTo returns true if transitioning from the current status
// to the target status is valid according to the state machine.
//
// Valid transitions:
//   - pending_review → approved, rejected
//   - approved → published
//   - rejected → pending_review (re-submission)
//   - published → (terminal, no transitions)
func (d *SkillDraft) CanTransitionTo(target SkillDraftStatus) bool {
	switch d.Status {
	case SkillDraftPendingReview:
		return target == SkillDraftApproved || target == SkillDraftRejected
	case SkillDraftApproved:
		return target == SkillDraftPublished
	case SkillDraftRejected:
		return target == SkillDraftPendingReview
	case SkillDraftPublished:
		return false
	default:
		return false
	}
}

// TransitionTo attempts to move the draft to the target status.
// It sets the appropriate timestamp fields (ReviewedAt, PublishedAt)
// and returns an error if the transition is invalid.
func (d *SkillDraft) TransitionTo(target SkillDraftStatus) error {
	if !d.CanTransitionTo(target) {
		return fmt.Errorf("invalid transition from %s to %s", d.Status, target)
	}
	now := time.Now().UTC()
	switch target {
	case SkillDraftApproved, SkillDraftRejected:
		d.ReviewedAt = &now
	case SkillDraftPublished:
		d.PublishedAt = &now
	}
	d.Status = target
	return nil
}
