package lht

import (
	"fmt"
	"math"
	"strings"
)

// BudgetEstimationInput gathers the parameters needed to estimate a budget.
type BudgetEstimationInput struct {
	GoalID       string
	Category     GoalCategory
	TaskCount    int
	MaxDepth     int    // max dependency depth in DAG
	Complexity   string // "low", "medium", "high"
}

// BudgetProposal is the recommended budget generated by the estimation engine.
// It is presented alongside the plan for user approval.
type BudgetProposal struct {
	GoalID           string  `json:"goal_id"`
	MaxRounds        int     `json:"max_rounds"`
	MaxTokens        int64   `json:"max_tokens"`
	MaxDurationHours float64 `json:"max_duration_hours"`
	Rationale        string  `json:"rationale"`

	// Breakdown for transparency
	BaselineRounds        int     `json:"baseline_rounds"`
	ComplexityMultiplier  float64 `json:"complexity_multiplier"`
	RetryCoefficient      float64 `json:"retry_coefficient"`
}

// WorkflowBaseline stores the baseline budget values per workflow type.
type WorkflowBaseline struct {
	RoundsPerTask int     // base rounds per task
	TokensPerTask int64   // base tokens per task
	HoursPerTask  float64 // base hours per task
}

// Baseline table v1: per-workflow-type baseline values.
var workflowBaselines = map[GoalCategory]WorkflowBaseline{
	CategoryProject: {RoundsPerTask: 5, TokensPerTask: 50000, HoursPerTask: 2.0},
	CategoryCode:    {RoundsPerTask: 3, TokensPerTask: 30000, HoursPerTask: 1.0},
	CategoryResearch:{RoundsPerTask: 4, TokensPerTask: 80000, HoursPerTask: 3.0},
	CategoryGeneral: {RoundsPerTask: 3, TokensPerTask: 40000, HoursPerTask: 1.5},
}

// Complexity multipliers.
const (
	ComplexityLow    = "low"
	ComplexityMedium = "medium"
	ComplexityHigh   = "high"
)

func complexityMultiplier(c string) float64 {
	switch strings.ToLower(c) {
	case ComplexityLow:
		return 0.7
	case ComplexityHigh:
		return 1.8
	default: // medium or unknown
		return 1.0
	}
}

// Default retry coefficient adds 25% overhead for retries.
const defaultRetryCoefficient = 1.25

// EstimateBudget generates a BudgetProposal from the estimation input.
// Formula: suggested = baseline_per_task * task_count * complexity * retry * depth_factor
func EstimateBudget(input BudgetEstimationInput) BudgetProposal {
	bl, ok := workflowBaselines[input.Category]
	if !ok {
		bl = workflowBaselines[CategoryGeneral]
	}

	cplx := complexityMultiplier(input.Complexity)
	depthFactor := depthMultiplier(input.MaxDepth)

	rounds := int(math.Ceil(float64(bl.RoundsPerTask) * float64(input.TaskCount) * cplx * defaultRetryCoefficient * depthFactor))
	tokens := int64(math.Ceil(float64(bl.TokensPerTask) * float64(input.TaskCount) * cplx * defaultRetryCoefficient * depthFactor))
	hours := float64(bl.HoursPerTask) * float64(input.TaskCount) * cplx * defaultRetryCoefficient * depthFactor
	// Round hours to 1 decimal
	hours = math.Round(hours*10) / 10

	rationale := fmt.Sprintf(
		"类型=%s 子任务=%d 深度=%d 复杂度=%s → 基线%.0f×任务数×复杂度%.2f×重试%.2f×深度%.1f",
		input.Category, input.TaskCount, input.MaxDepth, input.Complexity,
		float64(bl.RoundsPerTask), cplx, defaultRetryCoefficient, depthFactor,
	)

	return BudgetProposal{
		GoalID:               input.GoalID,
		MaxRounds:            rounds,
		MaxTokens:            tokens,
		MaxDurationHours:     hours,
		Rationale:            rationale,
		BaselineRounds:       bl.RoundsPerTask,
		ComplexityMultiplier: cplx,
		RetryCoefficient:     defaultRetryCoefficient,
	}
}

// depthMultiplier adds overhead based on DAG depth: 1.0 at depth 0, +0.15 per level.
func depthMultiplier(depth int) float64 {
	if depth <= 0 {
		return 1.0
	}
	if depth > 10 {
		depth = 10
	}
	return 1.0 + float64(depth)*0.15
}

// ToBudget converts a BudgetProposal into a runtime Budget with Max* fields set.
func (bp BudgetProposal) ToBudget() Budget {
	return Budget{
		GoalID:           bp.GoalID,
		MaxRounds:        bp.MaxRounds,
		MaxTokens:        bp.MaxTokens,
		MaxDurationHours: bp.MaxDurationHours,
		UsedRounds:       0,
		UsedTokens:       0,
		UsedHours:        0,
	}
}

// --- Budget usage tracking ---

// TrackRound increments UsedRounds and returns false if the budget was already
// exhausted before this call. The call that reaches exactly the limit is allowed;
// only subsequent calls beyond the limit are rejected.
func (b *Budget) TrackRound() bool {
	if b.IsExhausted() {
		return false
	}
	b.UsedRounds++
	return true
}

// TrackTokens adds tokens to UsedTokens and returns false if the budget was already
// exhausted before this call.
func (b *Budget) TrackTokens(tokens int64) bool {
	if b.IsExhausted() {
		return false
	}
	b.UsedTokens += tokens
	return !b.IsExhausted()
}

// TrackHours adds hours to UsedHours and returns false if the budget was already
// exhausted before this call.
func (b *Budget) TrackHours(hours float64) bool {
	if b.IsExhausted() {
		return false
	}
	b.UsedHours += hours
	return !b.IsExhausted()
}

// Remaining returns the remaining budget in each dimension.
// A zero max value means no limit on that dimension.
func (b Budget) Remaining() (rounds int, tokens int64, hours float64) {
	if b.MaxRounds > 0 {
		rounds = b.MaxRounds - b.UsedRounds
		if rounds < 0 {
			rounds = 0
		}
	} else {
		rounds = -1 // unlimited
	}
	if b.MaxTokens > 0 {
		tokens = b.MaxTokens - b.UsedTokens
		if tokens < 0 {
			tokens = 0
		}
	} else {
		tokens = -1 // unlimited
	}
	if b.MaxDurationHours > 0 {
		hours = b.MaxDurationHours - b.UsedHours
		if hours < 0 {
			hours = 0
		}
	} else {
		hours = -1 // unlimited
	}
	return
}

// IsApproachingLimit returns true when any dimension is at threshold% or more
// of its configured max. A zero max value is never approaching.
func (b Budget) IsApproachingLimit(threshold float64) bool {
	if b.MaxRounds > 0 && float64(b.UsedRounds)/float64(b.MaxRounds) >= threshold {
		return true
	}
	if b.MaxTokens > 0 && float64(b.UsedTokens)/float64(b.MaxTokens) >= threshold {
		return true
	}
	if b.MaxDurationHours > 0 && b.UsedHours/b.MaxDurationHours >= threshold {
		return true
	}
	return false
}

// UsageReport returns a human-readable budget usage summary.
func (b Budget) UsageReport() string {
	rRem, tRem, hRem := b.Remaining()

	parts := []string{
		fmt.Sprintf("预算报告 [%s]", b.GoalID),
	}
	if b.MaxRounds > 0 {
		parts = append(parts, fmt.Sprintf("轮次: %d/%d (剩余 %d)", b.UsedRounds, b.MaxRounds, rRem))
	} else {
		parts = append(parts, fmt.Sprintf("轮次: %d/∞", b.UsedRounds))
	}
	if b.MaxTokens > 0 {
		parts = append(parts, fmt.Sprintf("Token: %d/%d (剩余 %d)", b.UsedTokens, b.MaxTokens, tRem))
	} else {
		parts = append(parts, fmt.Sprintf("Token: %d/∞", b.UsedTokens))
	}
	if b.MaxDurationHours > 0 {
		parts = append(parts, fmt.Sprintf("时长: %.1fh/%.1fh (剩余 %.1fh)", b.UsedHours, b.MaxDurationHours, hRem))
	} else {
		parts = append(parts, fmt.Sprintf("时长: %.1fh/∞", b.UsedHours))
	}

	return fmt.Sprintf("[%s] 预算使用 | %s", b.GoalID, strings.Join(parts, " | "))
}

// ResetUsage resets all usage counters to zero (used when budget is re-approved
// after replanning).
func (b *Budget) ResetUsage() {
	b.UsedRounds = 0
	b.UsedTokens = 0
	b.UsedHours = 0
}
